export const CREDIT_NAME = 'DJMoneyKey';
export const CREDIT_LABEL = `by ${CREDIT_NAME}`;
export const CREDIT_REVEAL_INTERVAL_MS = 5 * 60_000;
export const CREDIT_REVEAL_DURATION_MS = 5_000;
export const CREDIT_REVEAL_EVERY_MINUTES = CREDIT_REVEAL_INTERVAL_MS / 60_000;
export const CREDIT_REVEAL_FOR_SECONDS = CREDIT_REVEAL_DURATION_MS / 1_000;
